name: timer_web
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  auto_size_text: ^3.0.0
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  flutter_switch: ^0.3.2
  google_fonts: ^6.2.1
  just_audio: ^0.9.46

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Imagens/
    - assets/Figma/
    - assets/Ãcones/
    - assets/Logo/
    - assets/Sons/